# Site settings
title:       Duc Nguyen
email:       vietducnguyen.vn@gmail.com
author:      Duc Nguyen
description: "My Blog"
baseurl:     ""
url:         "http://nguyenvietduc.com"

# Google analytics
google_analytics: UA-17272463-6

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: nguyenvietduc
stackoverflow_id:
twitter_username: nguyenvietduc
google_plus_id:
linkedin_username: nguyenvietduc
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share is caring!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:categories/:title
paginate:     3
sass:
  compressed: true
